- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes



- name: Update our website from a GIT repository.
  git:
    repo: https://github.com/JasonWorger/SFIA_Project_Week_9.git
    dest: "{{ install_directory }}"



- name: Init a new swarm with default parameters
  docker_swarm:
    state: present

- name: Gathering join token 
  docker_swarm:
    state: inspect
  register: swarm_info

- name: Verifying that swarm nodes are present
  docker_swarm_info:
    nodes: yes

- name: Joining worker nodes to manager 
  add_host:
    name: "join_token"
    value: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"
  


